{% set name = "trame-vuetify" %}
{% set version = "2.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-vuetify-{{ version }}.tar.gz
  sha256: 41316c16cf6af2446e980a0bbc32a549209bb27cc5fd4d18b87945e607ccc69a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - trame-client

test:
  imports:
    - trame
    - trame.modules
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/trame-vuetify/
  summary: Vuetify widgets for trame
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
