{% set name = "trame-vuetify" %}
{% set version = "3.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cdef8316d7e7100a6a35aa6d76dd03263956041b534578ba9218f316ffc7d9f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - trame-client

test:
  imports:
    - trame
    - trame.modules
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/trame-vuetify/
  summary: Vuetify widgets for trame
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - jourdain
    - psavery
    - kwrobot
